os:
  - linux

dist: bionic

language: php

php:
  - '7.2'

install:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpcs app --standard=phpcs/TickrStandard