language: php

php:
  - '7.2.2'

before_install:
  - cp src/.env.travis src/.env

install:
  - composer self-update
  - composer install --no-interaction --working-dir src/

script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit
